apiVersion: v1
data:
  index.html: |
    MYSQL_DATABASE: "mysql://username:password@host/27017"
    MYSQL_ROOT_PASSWORD: "ghanem"

kind: ConfigMap
metadata:
  namespace: test
  name: nginx-cm-file  # configmap-name
